// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type XdpDecapDecapConfig struct {
	MulticastIp   uint32
	ShredPort     uint16
	HeartbeatPort uint16
}

type XdpDecapDecapStats struct {
	Decapped uint64
	Passed   uint64
	Errors   uint64
}

// LoadXdpDecap returns the embedded CollectionSpec for XdpDecap.
func LoadXdpDecap() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpDecapBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load XdpDecap: %w", err)
	}

	return spec, err
}

// LoadXdpDecapObjects loads XdpDecap and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*XdpDecapObjects
//	*XdpDecapPrograms
//	*XdpDecapMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadXdpDecapObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadXdpDecap()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// XdpDecapSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpDecapSpecs struct {
	XdpDecapProgramSpecs
	XdpDecapMapSpecs
	XdpDecapVariableSpecs
}

// XdpDecapProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpDecapProgramSpecs struct {
	XdpDecap *ebpf.ProgramSpec `ebpf:"xdp_decap"`
}

// XdpDecapMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpDecapMapSpecs struct {
	Config *ebpf.MapSpec `ebpf:"config"`
	Stats  *ebpf.MapSpec `ebpf:"stats"`
}

// XdpDecapVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpDecapVariableSpecs struct {
}

// XdpDecapObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadXdpDecapObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpDecapObjects struct {
	XdpDecapPrograms
	XdpDecapMaps
	XdpDecapVariables
}

func (o *XdpDecapObjects) Close() error {
	return _XdpDecapClose(
		&o.XdpDecapPrograms,
		&o.XdpDecapMaps,
	)
}

// XdpDecapMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadXdpDecapObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpDecapMaps struct {
	Config *ebpf.Map `ebpf:"config"`
	Stats  *ebpf.Map `ebpf:"stats"`
}

func (m *XdpDecapMaps) Close() error {
	return _XdpDecapClose(
		m.Config,
		m.Stats,
	)
}

// XdpDecapVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadXdpDecapObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpDecapVariables struct {
}

// XdpDecapPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadXdpDecapObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpDecapPrograms struct {
	XdpDecap *ebpf.Program `ebpf:"xdp_decap"`
}

func (p *XdpDecapPrograms) Close() error {
	return _XdpDecapClose(
		p.XdpDecap,
	)
}

func _XdpDecapClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpdecap_bpfel.o
var _XdpDecapBytes []byte
