//! The four findings, each injected deliberately, and the fourth asserted to
//! produce none.
//!
//! Every expected wire value below is written out by hand. The bit positions,
//! the enumerated bytes and the sentinels are transcribed from the
//! specifications' own field tables — `Update Flags` bit 0 is *bid updated* and
//! bit 2 is *bid gone*; `Action` numbers from `Unknown = 0`; `Order Count` and
//! `Level Index` say *absent* with `0xFFFF` while top-of-book's `Source Count`
//! says it with `0` — and the scaled integers are the venue's decimals shifted
//! by the archived exponent, computed by hand. Nothing here is produced by the
//! lowering this comparison re-runs: a control generated by the code under test
//! is not a control.

mod common;

use common::{
    pack, payloads, refdata_datagrams, DatagramLog, Framing, LineAdapter, Listed, Msg, CHANNEL_ID,
    SOURCE_ID,
};
use dz_edge_mbp::{BookClear, LevelUpdate, MarketByPrice, MAGIC_MBP};
use dz_edge_tob::{Quote, TopOfBook, Trade, MAGIC_TOB};
use dz_recorder_relower::{compare_archives, Finding, JoinKey, Outcome, TopOfBookTie};

/// One instrument: prices at two decimal places, quantities at none.
const AAA: Listed = Listed::new("AAA", 11, -2, 0);

// The wire values, by hand.
//
// `Side`: bid 0, ask 1. `Action`: unknown 0, new 1, change 2, delete 3.
// `Clear Side`: bid 0, ask 1, both 2. `Scope`: entire side 0, from price 1.
// `Order Count` and `Level Index` absent: 0xFFFF.
const SIDE_BID: u8 = 0;
const SIDE_ASK: u8 = 1;
const ACTION_UNKNOWN: u8 = 0;
const ACTION_NEW: u8 = 1;
const ACTION_CHANGE: u8 = 2;
const ACTION_DELETE: u8 = 3;
const CLEAR_ASK: u8 = 1;
const SCOPE_ENTIRE_SIDE: u8 = 0;
const ABSENT_U16: u16 = 0xFFFF;

/// `Update Flags`: bid updated 0x01, ask updated 0x02, bid gone 0x04, ask gone
/// 0x08. The two bits of a side are mutually exclusive.
const BOTH_UPDATED: u8 = 0x03;
const BID_GONE_ASK_UPDATED: u8 = 0x06;

/// `Aggressor Side`: unknown 0, buy 1, sell 2.
const AGGRESSOR_BUY: u8 = 1;

/// The upstream window every depth test replays.
///
/// The last line is a heartbeat, which produces no event: a payload that
/// becomes nothing must not become a finding.
const DEPTH_PAYLOADS: [&str; 5] = [
    "l AAA 1000000003 bid 99.50 12 new",
    "l AAA 1000000004 ask 100.50 7 unknown",
    "l AAA 1000000005 bid 99.50 0 change",
    "c AAA 1000000006 ask",
    "h",
];

fn level(seq: u32, side: u8, action: u8, price_raw: i64, qty_raw: u64, ts: u64) -> LevelUpdate {
    LevelUpdate {
        instrument_id: AAA.instrument_id,
        source_id: SOURCE_ID,
        side,
        action,
        per_instrument_seq: seq,
        price_raw,
        qty_raw,
        timestamp_ns: ts,
        order_count: ABSENT_U16,
        level_index: ABSENT_U16,
        update_reason: 0,
        level_flags: 0,
    }
}

fn clear(seq: u32, ts: u64) -> BookClear {
    BookClear {
        instrument_id: AAA.instrument_id,
        source_id: SOURCE_ID,
        clear_side: CLEAR_ASK,
        scope: SCOPE_ENTIRE_SIDE,
        per_instrument_seq: seq,
        from_price_raw: 0,
        timestamp_ns: ts,
        clear_reason: 0,
    }
}

/// What a correct publisher put on the wire for [`DEPTH_PAYLOADS`].
///
/// `Per-Instrument Seq` counts 1, 2, 3, 4 across the level updates *and* the
/// clear, because both mutate the book and share one series.
fn depth_on_the_wire() -> Vec<Msg> {
    vec![
        Msg::Level(level(1, SIDE_BID, ACTION_NEW, 9_950, 12, 1_000_000_003)),
        Msg::Level(level(2, SIDE_ASK, ACTION_UNKNOWN, 10_050, 7, 1_000_000_004)),
        Msg::Level(level(3, SIDE_BID, ACTION_DELETE, 9_950, 0, 1_000_000_005)),
        Msg::Clear(clear(4, 1_000_000_006)),
    ]
}

/// An archive holding the depth feed's reference data and the messages given.
fn depth_archive(messages: &[Msg], framing: Framing) -> DatagramLog {
    let mut archive = DatagramLog::new(refdata_datagrams::<MarketByPrice>(&[AAA], 1));
    archive.extend(pack::<MarketByPrice>(
        messages,
        dz_edge_core::PortRole::Mktdata,
        framing,
    ));
    archive
}

#[test]
fn framing_and_pacing_differences_alone_produce_no_finding() {
    // The fourth outcome, and the test that keeps the tool usable. The wire
    // carries exactly the messages the re-lowering produces, and everything
    // about *how* differs: five messages to a datagram instead of one, a
    // sequence space starting nine thousand later, a different era, a send clock
    // 100 seconds ahead stepping quarter-seconds, and the datagrams delivered
    // out of order. A comparison at datagram grain would report all of it.
    let mut archive = depth_archive(&depth_on_the_wire(), Framing::batched(5));
    archive.rotate(1);
    let mut adapter = LineAdapter::over(&[AAA]);
    let mut upstream = payloads(&DEPTH_PAYLOADS);

    let report = compare_archives(&mut adapter, &mut upstream, &mut archive, MAGIC_MBP)
        .expect("both archives are complete");

    assert!(
        report.is_clean(),
        "framing and pacing produced findings: {:?}",
        report
            .findings
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
    );
    // And it compared something: a clean report over an empty join is the
    // failure mode a bare `is_clean` would not catch.
    assert_eq!(report.summary.identical, 4);
    assert_eq!(report.summary.on_wire, 4);
    assert_eq!(report.summary.re_lowered, 4);
    assert_eq!(report.summary.of(Outcome::IdenticalDifferentTiming), 4);
}

#[test]
fn a_message_the_publisher_did_not_send_is_reported_as_re_lowered_not_on_wire() {
    // The venue's events produce four messages; the archive holds three. The
    // second level update — the one the publisher dropped — is named by its own
    // join key rather than by a position, which is what makes the finding
    // actionable at all.
    let mut wire = depth_on_the_wire();
    let dropped = wire.remove(1);
    assert!(matches!(dropped, Msg::Level(_)));

    let mut archive = depth_archive(&wire, Framing::tight());
    let mut adapter = LineAdapter::over(&[AAA]);
    let mut upstream = payloads(&DEPTH_PAYLOADS);

    let report = compare_archives(&mut adapter, &mut upstream, &mut archive, MAGIC_MBP)
        .expect("both archives are complete");

    assert_eq!(report.findings.len(), 1, "{:?}", report.findings);
    match &report.findings[0] {
        Finding::ReLoweredNotOnWire {
            key,
            message_type,
            re_lowered,
        } => {
            assert_eq!(
                *key,
                JoinKey::Depth {
                    instrument_id: 11,
                    per_instrument_seq: 2,
                }
            );
            assert_eq!(*message_type, "LevelUpdate");
            // The payload that produced it, so an operator can replay exactly
            // those upstream bytes.
            assert_eq!(re_lowered.payload_index, 1);
            assert_eq!(re_lowered.event_index, 0);
        }
        other => panic!("expected the publisher's own drop, got {other}"),
    }
    assert_eq!(report.summary.identical, 3);
    assert_eq!(report.summary.re_lowered_not_on_wire, 1);
}

#[test]
fn a_message_the_venue_never_sent_is_reported_as_on_wire_not_re_lowered() {
    // A fifth message on the wire that no upstream payload accounts for: the
    // publisher invented it, or its reference-data state diverged from what it
    // published.
    let mut wire = depth_on_the_wire();
    wire.push(Msg::Level(level(
        5,
        SIDE_ASK,
        ACTION_NEW,
        10_075,
        3,
        1_000_000_007,
    )));

    let mut archive = depth_archive(&wire, Framing::tight());
    let mut adapter = LineAdapter::over(&[AAA]);
    let mut upstream = payloads(&DEPTH_PAYLOADS);

    let report = compare_archives(&mut adapter, &mut upstream, &mut archive, MAGIC_MBP)
        .expect("both archives are complete");

    assert_eq!(report.findings.len(), 1, "{:?}", report.findings);
    match &report.findings[0] {
        Finding::OnWireNotReLowered {
            key,
            message_type,
            wire,
        } => {
            assert_eq!(
                *key,
                JoinKey::Depth {
                    instrument_id: 11,
                    per_instrument_seq: 5,
                }
            );
            assert_eq!(*message_type, "LevelUpdate");
            assert_eq!(wire.channel_id, CHANNEL_ID);
            // The datagram it was in, so the archive can be opened at it:
            // counted over everything the source yielded, which here is two
            // reference-data datagrams, then the four the venue's events
            // account for, then this one.
            assert_eq!(wire.datagram_index, 6);
        }
        other => panic!("expected an invented message, got {other}"),
    }
    // Nothing in the re-lowering was refused, so the absence is not ours.
    assert!(report.refusals.is_empty());
    assert_eq!(report.summary.identical, 4);
}

#[test]
fn a_price_scaled_at_the_wrong_exponent_is_reported_by_field() {
    // The publisher published 99.5 at an exponent one place short of the one its
    // own definition declares — the single commonest scaling defect, and the one
    // a round-trip test cannot see because the encoder and the decoder agree.
    let mut wire = depth_on_the_wire();
    wire[0] = Msg::Level(level(1, SIDE_BID, ACTION_NEW, 995, 12, 1_000_000_003));

    let mut archive = depth_archive(&wire, Framing::tight());
    let mut adapter = LineAdapter::over(&[AAA]);
    let mut upstream = payloads(&DEPTH_PAYLOADS);

    let report = compare_archives(&mut adapter, &mut upstream, &mut archive, MAGIC_MBP)
        .expect("both archives are complete");

    assert_eq!(report.findings.len(), 1, "{:?}", report.findings);
    match &report.findings[0] {
        Finding::FieldsDiffer {
            key,
            message_type,
            fields,
            ..
        } => {
            assert_eq!(
                *key,
                JoinKey::Depth {
                    instrument_id: 11,
                    per_instrument_seq: 1,
                }
            );
            assert_eq!(*message_type, "LevelUpdate");
            assert_eq!(fields.len(), 1, "{fields:?}");
            assert_eq!(fields[0].field, "price_raw");
            assert_eq!(fields[0].on_wire, "995");
            assert_eq!(fields[0].re_lowered, "9950");
            // The rendered row names the field, because that is what an
            // operator reads.
            assert!(report.findings[0].to_string().contains("price_raw"));
        }
        other => panic!("expected a field difference, got {other}"),
    }
    assert_eq!(report.summary.fields_differ, 1);
    assert_eq!(report.summary.identical, 3);
}

#[test]
fn an_action_table_numbered_from_new_is_reported_by_field() {
    // The shipped defect this whole boundary was shaped around: a publisher
    // numbering the `Action` table from `New` instead of `Unknown` emits every
    // removal as a `Change` carrying zero. Self-consistent, so invisible to any
    // encode-then-decode test — subscribers apply by quantity and build correct
    // books while every consumer reading the field is quietly wrong. Here the
    // other side of the comparison derives the byte from the quantity, so it is
    // one finding naming one field.
    let mut wire = depth_on_the_wire();
    wire[2] = Msg::Level(level(3, SIDE_BID, ACTION_CHANGE, 9_950, 0, 1_000_000_005));

    let mut archive = depth_archive(&wire, Framing::tight());
    let mut adapter = LineAdapter::over(&[AAA]);
    let mut upstream = payloads(&DEPTH_PAYLOADS);

    let report = compare_archives(&mut adapter, &mut upstream, &mut archive, MAGIC_MBP)
        .expect("both archives are complete");

    assert_eq!(report.findings.len(), 1, "{:?}", report.findings);
    let Finding::FieldsDiffer { fields, .. } = &report.findings[0] else {
        panic!("expected a field difference, got {}", report.findings[0]);
    };
    assert_eq!(fields.len(), 1, "{fields:?}");
    assert_eq!(fields[0].field, "action");
    assert_eq!(fields[0].on_wire, "2 (0x02)");
    assert_eq!(fields[0].re_lowered, "3 (0x03)");
}

#[test]
fn a_book_clear_where_the_venue_said_a_level_is_one_finding_naming_the_type() {
    // Two message types at one key. Reported as a difference in the type rather
    // than as two absences, because the publisher and the re-lowering agree
    // about *which* upstream event this is.
    let mut wire = depth_on_the_wire();
    wire[1] = Msg::Clear(clear(2, 1_000_000_004));

    let mut archive = depth_archive(&wire, Framing::tight());
    let mut adapter = LineAdapter::over(&[AAA]);
    let mut upstream = payloads(&DEPTH_PAYLOADS);

    let report = compare_archives(&mut adapter, &mut upstream, &mut archive, MAGIC_MBP)
        .expect("both archives are complete");

    assert_eq!(report.findings.len(), 1, "{:?}", report.findings);
    let Finding::FieldsDiffer { fields, .. } = &report.findings[0] else {
        panic!("expected a field difference, got {}", report.findings[0]);
    };
    assert_eq!(fields.len(), 1, "{fields:?}");
    assert_eq!(fields[0].field, "message_type");
    assert_eq!(fields[0].on_wire, "BookClear");
    assert_eq!(fields[0].re_lowered, "LevelUpdate");
}

// ---------------------------------------------------------------------------
// Top-of-book: the other key space.
// ---------------------------------------------------------------------------

const TOB_PAYLOADS: [&str; 3] = [
    "q AAA 1000000001 99.50 12 100.50 7",
    "q AAA 1000000002 - - 100.75 3",
    "t AAA 1000000005 100.25 2 buy 7788",
];

fn quote(ts: u64, flags: u8, bid_price: i64, bid_qty: u64, ask_price: i64, ask_qty: u64) -> Quote {
    Quote {
        instrument_id: AAA.instrument_id,
        source_id: SOURCE_ID,
        update_flags: flags,
        source_timestamp_ns: ts,
        bid_price,
        bid_qty,
        ask_price,
        ask_qty,
        // Top-of-book says *unavailable* with zero, which is the opposite of the
        // depth feed's `0xFFFF`. Two specifications, one question, opposite
        // answers.
        bid_source_count: 0,
        ask_source_count: 0,
    }
}

fn tob_on_the_wire() -> Vec<Msg> {
    vec![
        Msg::Quote(quote(1_000_000_001, BOTH_UPDATED, 9_950, 12, 10_050, 7)),
        // A gone side is a zero price and a zero quantity, and the flag is what
        // says so: zero is an in-range price on the wire.
        Msg::Quote(quote(1_000_000_002, BID_GONE_ASK_UPDATED, 0, 0, 10_075, 3)),
        Msg::Trade(Trade {
            instrument_id: AAA.instrument_id,
            source_id: SOURCE_ID,
            aggressor_side: AGGRESSOR_BUY,
            trade_flags: 0,
            source_timestamp_ns: 1_000_000_005,
            trade_price: 10_025,
            trade_qty: 2,
            trade_id: 7788,
            cumulative_volume: 0,
        }),
    ]
}

fn tob_archive(messages: &[Msg], framing: Framing) -> DatagramLog {
    let mut archive = DatagramLog::new(refdata_datagrams::<TopOfBook>(&[AAA], 1));
    archive.extend(pack::<TopOfBook>(
        messages,
        dz_edge_core::PortRole::Mktdata,
        framing,
    ));
    archive
}

#[test]
fn a_top_of_book_window_that_agrees_produces_no_finding() {
    let mut archive = tob_archive(&tob_on_the_wire(), Framing::batched(3));
    archive.rotate(1);
    let mut adapter = LineAdapter::over(&[AAA]);
    let mut upstream = payloads(&TOB_PAYLOADS);

    let report = compare_archives(&mut adapter, &mut upstream, &mut archive, MAGIC_TOB)
        .expect("both archives are complete");

    assert!(report.is_clean(), "{:?}", report.findings);
    assert_eq!(report.summary.identical, 3);
}

#[test]
fn a_quote_joins_on_instrument_timestamp_and_update_flags() {
    // The design's own key for this feed, asserted as a key and not as a
    // behaviour: the second quote carries a gone bid, so its flags byte differs
    // from the first's, and the key says so.
    let mut wire = tob_on_the_wire();
    wire.remove(1);

    let mut archive = tob_archive(&wire, Framing::tight());
    let mut adapter = LineAdapter::over(&[AAA]);
    let mut upstream = payloads(&TOB_PAYLOADS);

    let report = compare_archives(&mut adapter, &mut upstream, &mut archive, MAGIC_TOB)
        .expect("both archives are complete");

    assert_eq!(report.findings.len(), 1, "{:?}", report.findings);
    assert_eq!(
        *report.findings[0].key(),
        JoinKey::TopOfBook {
            instrument_id: 11,
            source_timestamp_ns: 1_000_000_002,
            tie: TopOfBookTie::UpdateFlags(BID_GONE_ASK_UPDATED),
        }
    );
}

#[test]
fn a_quote_whose_gone_side_the_publisher_wrote_as_updated_is_two_findings_not_one() {
    // `Update Flags` is part of the top-of-book key, so a publisher that got the
    // byte wrong has not produced a differing copy of one message: it has
    // produced a message at a key the venue's events never reach. That is the
    // honest reading — the two copies are not the same message — and it is
    // stated here so that nobody reads the resulting pair of findings as a
    // defect in the join.
    let mut wire = tob_on_the_wire();
    wire[1] = Msg::Quote(quote(1_000_000_002, BOTH_UPDATED, 0, 0, 10_075, 3));

    let mut archive = tob_archive(&wire, Framing::tight());
    let mut adapter = LineAdapter::over(&[AAA]);
    let mut upstream = payloads(&TOB_PAYLOADS);

    let report = compare_archives(&mut adapter, &mut upstream, &mut archive, MAGIC_TOB)
        .expect("both archives are complete");

    assert_eq!(report.findings.len(), 2, "{:?}", report.findings);
    let outcomes: Vec<Outcome> = report
        .findings
        .iter()
        .map(dz_recorder_relower::Finding::outcome)
        .collect();
    assert!(outcomes.contains(&Outcome::OnWireNotReLowered));
    assert!(outcomes.contains(&Outcome::ReLoweredNotOnWire));
}
