package main

import (
	"encoding/binary"
	"fmt"
	"net"
	"os"

	"github.com/cilium/ebpf/link"
)

// XdpHandle holds the loaded eBPF objects and XDP link.
type XdpHandle struct {
	Objs      XdpFilterObjects // generated by bpf2go
	Link      link.Link
	Interface string
}

// Close detaches the XDP program and releases eBPF resources.
func (h *XdpHandle) Close() {
	fmt.Fprintf(os.Stderr, "Detaching XDP program from %s...\n", h.Interface)
	if h.Link != nil {
		h.Link.Close()
	}
	h.Objs.Close()
}

// AttachXDP loads the eBPF program, attaches it to the configured interface,
// and writes the filter configuration into the CONFIG map.
func AttachXDP(cfg *Config) (*XdpHandle, string, error) {
	var objs XdpFilterObjects
	if err := LoadXdpFilterObjects(&objs, nil); err != nil {
		return nil, "", fmt.Errorf("load eBPF objects: %w", err)
	}

	iface, err := net.InterfaceByName(cfg.Network.PhysicalInterface)
	if err != nil {
		objs.Close()
		return nil, "", fmt.Errorf("interface %q: %w", cfg.Network.PhysicalInterface, err)
	}

	var l link.Link
	var actualMode string

	switch cfg.Xdp.XdpMode {
	case XdpModeNative:
		l, err = link.AttachXDP(link.XDPOptions{
			Program:   objs.XdpFilter,
			Interface: iface.Index,
			Flags:     link.XDPDriverMode,
		})
		actualMode = "native"
	case XdpModeSkb:
		l, err = link.AttachXDP(link.XDPOptions{
			Program:   objs.XdpFilter,
			Interface: iface.Index,
			Flags:     link.XDPGenericMode,
		})
		actualMode = "skb"
	default: // auto: try native first, fall back to skb
		l, err = link.AttachXDP(link.XDPOptions{
			Program:   objs.XdpFilter,
			Interface: iface.Index,
			Flags:     link.XDPDriverMode,
		})
		actualMode = "native"
		if err != nil {
			fmt.Fprintf(os.Stderr, "Native XDP attach failed (%v), trying SKB mode\n", err)
			// Reload objects for clean state.
			objs.Close()
			if err2 := LoadXdpFilterObjects(&objs, nil); err2 != nil {
				return nil, "", fmt.Errorf("reload eBPF objects: %w", err2)
			}
			l, err = link.AttachXDP(link.XDPOptions{
				Program:   objs.XdpFilter,
				Interface: iface.Index,
				Flags:     link.XDPGenericMode,
			})
			actualMode = "skb"
		}
	}
	if err != nil {
		objs.Close()
		return nil, "", fmt.Errorf("attach XDP (%s mode): %w", actualMode, err)
	}

	// Write filter config to CONFIG map.
	ip := net.ParseIP(cfg.Network.MulticastGroup).To4()
	if ip == nil {
		l.Close()
		objs.Close()
		return nil, "", fmt.Errorf("invalid multicast IP: %s", cfg.Network.MulticastGroup)
	}
	ipU32 := binary.BigEndian.Uint32(ip) // network byte order, matching eBPF
	filterCfg := XdpFilterFilterConfig{
		MulticastIp:   ipU32,
		ShredPort:     cfg.Network.ShredPort,
		HeartbeatPort: cfg.Network.HeartbeatPort,
	}
	if err := objs.Config.Put(uint32(0), filterCfg); err != nil {
		l.Close()
		objs.Close()
		return nil, "", fmt.Errorf("write filter config: %w", err)
	}

	fmt.Fprintf(os.Stderr, "XDP program attached to %s (mode: %s)\n", cfg.Network.PhysicalInterface, actualMode)

	return &XdpHandle{
		Objs:      objs,
		Link:      l,
		Interface: cfg.Network.PhysicalInterface,
	}, actualMode, nil
}

// RegisterXskSocket registers an AF_XDP socket file descriptor in the XSKMAP.
func RegisterXskSocket(objs *XdpFilterObjects, queueID uint32, fd int) error {
	return objs.Xskmap.Put(queueID, uint32(fd))
}

// ReadXdpStats reads the per-CPU stats from the STATS map and aggregates them.
func ReadXdpStats(objs *XdpFilterObjects) (redirected, passed, errors uint64, err error) {
	var perCPU []XdpFilterXdpStats
	if err := objs.Stats.Lookup(uint32(0), &perCPU); err != nil {
		return 0, 0, 0, fmt.Errorf("lookup stats: %w", err)
	}
	for _, v := range perCPU {
		redirected += v.Redirected
		passed += v.Passed
		errors += v.Errors
	}
	return redirected, passed, errors, nil
}
