// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type XdpFilterFilterConfig struct {
	MulticastIp   uint32
	ShredPort     uint16
	HeartbeatPort uint16
}

type XdpFilterXdpStats struct {
	Redirected uint64
	Passed     uint64
	Errors     uint64
}

// LoadXdpFilter returns the embedded CollectionSpec for XdpFilter.
func LoadXdpFilter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpFilterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load XdpFilter: %w", err)
	}

	return spec, err
}

// LoadXdpFilterObjects loads XdpFilter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*XdpFilterObjects
//	*XdpFilterPrograms
//	*XdpFilterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadXdpFilterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadXdpFilter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// XdpFilterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpFilterSpecs struct {
	XdpFilterProgramSpecs
	XdpFilterMapSpecs
	XdpFilterVariableSpecs
}

// XdpFilterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpFilterProgramSpecs struct {
	XdpFilter *ebpf.ProgramSpec `ebpf:"xdp_filter"`
}

// XdpFilterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpFilterMapSpecs struct {
	Config *ebpf.MapSpec `ebpf:"config"`
	Stats  *ebpf.MapSpec `ebpf:"stats"`
	Xskmap *ebpf.MapSpec `ebpf:"xskmap"`
}

// XdpFilterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpFilterVariableSpecs struct {
}

// XdpFilterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadXdpFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpFilterObjects struct {
	XdpFilterPrograms
	XdpFilterMaps
	XdpFilterVariables
}

func (o *XdpFilterObjects) Close() error {
	return _XdpFilterClose(
		&o.XdpFilterPrograms,
		&o.XdpFilterMaps,
	)
}

// XdpFilterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadXdpFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpFilterMaps struct {
	Config *ebpf.Map `ebpf:"config"`
	Stats  *ebpf.Map `ebpf:"stats"`
	Xskmap *ebpf.Map `ebpf:"xskmap"`
}

func (m *XdpFilterMaps) Close() error {
	return _XdpFilterClose(
		m.Config,
		m.Stats,
		m.Xskmap,
	)
}

// XdpFilterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadXdpFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpFilterVariables struct {
}

// XdpFilterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadXdpFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpFilterPrograms struct {
	XdpFilter *ebpf.Program `ebpf:"xdp_filter"`
}

func (p *XdpFilterPrograms) Close() error {
	return _XdpFilterClose(
		p.XdpFilter,
	)
}

func _XdpFilterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpfilter_bpfeb.o
var _XdpFilterBytes []byte
