-- What may READ what the dashboards read, recorded where it can be re-applied.
--
-- Separate from `004` deliberately, and not because grants belong in two
-- places. `004` is the loader's ACCOUNT: it creates the user, sets the profile
-- and the quota that bound it, and its thesis is **no SELECT on anything** —
-- an account that cannot read cannot become the most expensive query on the
-- cluster. A reader granted inside that file would read as an exception to the
-- argument the file is making. This one holds the opposite kind of grant and
-- says so in its name.
--
-- WHY IT EXISTS AT ALL: these two grants were applied by hand on 2026-09-19,
-- against the shared ClickHouse, so that a Grafana dashboard could show the
-- venue rows — the datasource user could not read them, and the panels were
-- not empty so much as impossible. Nothing recorded that. A search of every
-- repository found no `GRANT` to this reader anywhere in SQL: its other
-- fifteen grants, across `feeds`, `lake`, `telemetry_*` and the rest, were all
-- applied the same way and are written down nowhere. So a rebuilt service comes
-- back with the tables and without the reader, and the symptom is half a
-- dashboard rendering nothing with no artefact that explains why.
--
-- THE READER IS NOT CREATED HERE, AND THAT IS THE DECISION MOST WORTH
-- DISAGREEING WITH. `grafana` is not this repository's account the way
-- `dz_loader` is. This repository defines the loader end to end — creates it,
-- bounds it, grants it, and rotates one secret for it. The reader spans
-- databases this repository has never heard of, and its password lives with
-- whoever provisioned the Grafana data source. A `CREATE USER IF NOT EXISTS`
-- here would be a no-op on the cluster that matters and, on a fresh one, would
-- manufacture an account with a password nobody holds — which is worse than
-- the failure below, because it succeeds.
--
-- SO THIS FILE FAILS ON A CLUSTER WHERE THE READER DOES NOT EXIST, BY DESIGN.
-- A grant names a user that has to exist when it is stored; `004`'s own
-- ordering rule is the same fact, asserted by
-- `the_account_file_creates_the_profile_before_the_user_that_names_it`. The
-- failure is the correct outcome: it says the reader is provisioned elsewhere
-- and that step has not run, which is a sentence an operator can act on. A file
-- that quietly created the account would say nothing and leave a login nobody
-- can use.
--
-- A grant naming a TABLE that does not exist yet is fine — ClickHouse stores a
-- grant against the name, not the object — so the ordering that matters here is
-- the reader's, never the schema's.
--
-- APPLIED BY AN ADMINISTRATOR, NOT BY ANYTHING THAT WRITES ROWS, which is why
-- `schema()` filters this file out alongside `004`. Granting needs
-- access-management rights, and the loader holding them is the thing `004`
-- exists to prevent.
--
--   clickhouse-client --queries-file 012_recorder_reader_grants.sql
--
-- Idempotent by construction: a grant the account already holds is replayed,
-- never doubled, so re-applying is always safe and is never a schema change.
--
-- THE STANDING RULE FROM `004` APPLIES HERE TOO: a later file that adds an
-- object the dashboards read — a table, a view, or a view over a view — adds
-- its `GRANT SELECT` to this list and says in its own header that this file has
-- to be applied again. A file that does not do so ships something the reader
-- cannot see, found when somebody opens a panel rather than in review.
--
-- "AN OBJECT" AND NOT "A VENUE TABLE", WHICH IS WHAT THIS PARAGRAPH SAID AND
-- HOW IT WAS READ PAST. A view is not a table and the publisher side of a race
-- is not a venue grain, so a file that added four views over both sides could
-- satisfy the rule as written by doing nothing at all.
--
-- `010` IS THAT FILE, AND IT IS WHY SIX OF THE NINE GRANTS BELOW ARRIVED LATE.
-- It declares `publisher_book_top_occurrence`, re-states `book_top_settled`
-- over the column it adds, and replaces the seam and the pairing with two-sided
-- definitions — four views a dashboard reads — and the only thing it says about
-- privilege is "NO GRANT CHANGE", which is true of `004` and of the loader's
-- INSERT and says nothing about this direction. Found exactly the way the rule
-- predicts: somebody opened a race panel and met `497`
-- (`malbeclabs/phoenix#290`). The rule stands; what it needed was something
-- other than a header to hold it, so `ddl.rs` now pairs every statement below
-- against the file that declares its object.
--
-- `011` IS CLEAR OF THE RULE, checked rather than assumed. It adds two columns
-- to `recorder.event`, declares no table and no view, and nothing selects from
-- `recorder.event` — so there is no object the reader could be missing, and its
-- own "NO GRANT CHANGE" is the whole truth about it.
--
-- SCOPED TO THE OBJECTS A DASHBOARD READS AND NOT TO `recorder.*`, matching
-- `004`'s table-level grants and matching what was actually applied. The cost
-- is the one `009` already documents for the loader: a new venue grain needs
-- its own line here, and so does every view a panel is moved onto. The benefit
-- is that the transport grains of `001` — which nothing reads through this
-- account today — do not quietly become readable because a wildcard was easier
-- to write.
--
-- IT IS NO LONGER SCOPED TO THE VENUE TABLES, WHICH IS THE SENTENCE THIS
-- PARAGRAPH USED TO MAKE, and the change is worth naming rather than editing
-- away. A race has two sides, and the other one is `005`'s `book_top`: the
-- first market-data grain this reader may read. Table level is what keeps that
-- from being the whole of `005` — `event` and `instrument` sit beside it and
-- stay unreadable, which one `GRANT SELECT ON recorder.*` would have ended.

-- A VIEW NEEDS ITS OWN GRANT, WHICH IS NOT OBVIOUS FROM THE TABLE'S. A grant on
-- `venue_book_top` does not reach `venue_book_top_settled`, and the server says
-- so exactly: `code: 497 ... necessary to have the grant SELECT for at least
-- one column on recorder.venue_book_top_settled`. Found when the dashboard's
-- counting panels were moved onto the settled view and returned nothing.
--
-- The settled view is what a COUNT must read. `venue_book_top` is a
-- `ReplacingMergeTree` and a re-derivation is a replace, so between it and the
-- merge that follows one top of book is in the table twice — and `009` is
-- explicit that the surplus copy does not inflate a count so much as
-- manufacture evidence of loss, because it pairs with nothing and reads as a
-- state the other observation point missed. A reader granted the table and not
-- the view gets the wrong number rather than an error, which is the outcome
-- worth spending a line to prevent.
--
-- AND SO DOES EVERY OBJECT UNDERNEATH IT, which is the same fact one level
-- further down and is what decides the length of the block below. These are
-- normal views: they hold no rows, they are expanded into the query that reads
-- them, and at the server's default — `SQL SECURITY INVOKER` for a view that is
-- not materialised — every object the expansion touches is read with the
-- privileges of whoever asked. So a grant on `feed_race` alone answers `497`
-- naming `feed_race_occurrence`, and a grant on both answers `497` naming the
-- next one down. The pair already in this file is that rule with two links
-- rather than a special case: `venue_book_top_settled` was granted BESIDE
-- `venue_book_top` and not instead of it, and both of them are read by one
-- `SELECT count()`.
--
-- SO THE LIST IS DERIVED FROM THE VIEW DEFINITIONS AND NOT FROM THE PANEL.
-- What a query names is one object; what it reads is the transitive closure of
-- `FROM` beneath that object, and only the first of those is visible to whoever
-- writes the panel. Read off `009` and `010`, a panel over `recorder.feed_race`
-- reaches eight:
--
--   feed_race                          `009`, re-stated by `010`
--     feed_race_occurrence             `009` venue-only, replaced by `010`
--       venue_book_top_occurrence      `009`
--         venue_book_top_settled       `009`
--           venue_book_top             `009`
--       publisher_book_top_occurrence  `010`
--         book_top_settled             `006`, re-stated by `010`
--           book_top                   `005`
--
-- `venue_object` is the ninth grant and is in no chain: it is a table a panel
-- names directly, and it is what this file was first written for.

-- LAKE IS NOT GRANTED, AND THIS IS THE RECORD OF WHY RATHER THAN AN OMISSION.
--
-- An earlier revision of this file granted these tables to `lake_api`, on the
-- reasoning that Lake's SQL editor and its MCP server would then reach them.
-- That was wrong twice, and review caught both:
--
-- 1. **WRONG ACCOUNT.** Lake's prod deployment configures TWO ClickHouse users,
--    and `lake_api` is not the one those consumers use. `api/handlers/query.go`
--    and `mcp.go`'s `execute_sql` both select `a.PublicQueryDB`, which prod
--    sets from `CLICKHOUSE_PUBLIC_QUERY_USERNAME=lake_public_query`;
--    `CLICKHOUSE_USERNAME=lake_api` is the connection Lake's own Go handlers
--    use, and no handler reads a venue grain. So the grant bought nothing,
--    while this file — whose job is to be the durable record — asserted that
--    both consumers worked. A record that is confidently wrong is worse than an
--    absent one.
--
-- 2. **AND THE OBVIOUS FIX IS A DISCLOSURE DECISION, NOT A CONFIGURATION ONE.**
--    Swapping the grantee to `lake_public_query` would publish these tables to
--    unauthenticated callers on the public internet. `POST /api/sql/query`,
--    `/api/query` and `/api/mcp` carry only `OptionalAuth` — which, in its own
--    words, "attaches user to context if authenticated, allows anonymous" —
--    behind a 100/min per-IP rate limit. `RequireInternalDomain` guards a
--    different route group, and `lake-api`'s load balancer is
--    `internet-facing`. Grafana's audience is its own login behind fixed
--    panels, which is why `grafana` below is a different question from this
--    one.
--
-- So nothing is granted to Lake here. Making these tables reachable from Lake
-- is a change to Lake's exposure — authentication on those routes, or a surface
-- built for public reading — and it belongs to whoever owns that decision. This
-- file records the finding so that the next person to ask "why can Lake not see
-- this?" is not told to add a grant.
--
-- `lake_admin` and the indexer are not granted either, for the plainer reason:
-- they write and reconcile Lake's own schema, nothing in them reads a venue
-- grain, and an account that does not need a privilege should not hold one —
-- `004`'s argument about the loader, applied to a reader.

-- THE LIVE CLUSTER HOLDS THREE GRANTS THE BLOCK BELOW DOES NOT, AND THIS IS
-- THEM. They were applied by hand to the shared ClickHouse on 2026-09-21, while
-- the reasoning was still that Lake's SQL editor read through `lake_api`:
--
--   GRANT SELECT ON recorder.venue_book_top TO lake_api;
--   GRANT SELECT ON recorder.venue_object TO lake_api;
--   GRANT SELECT ON recorder.venue_book_top_settled TO lake_api;
--
-- They reach no consumer, because no Lake handler reads a venue grain, and they
-- want revoking:
--
--   REVOKE SELECT ON recorder.venue_book_top FROM lake_api;
--   REVOKE SELECT ON recorder.venue_object FROM lake_api;
--   REVOKE SELECT ON recorder.venue_book_top_settled FROM lake_api;
--
-- RECORDED HERE AND NOT APPLIED HERE, WHICH IS THE OPPOSITE DECISION FROM THE
-- GRANTS AND SO WANTS ITS REASON. Re-applying this file replays a grant and
-- revokes nothing, so without these lines an operator reads the block below as
-- the state of Lake's access while the cluster holds three more. A `REVOKE`
-- statement would close that for whoever re-applies the file, at two costs. It
-- names `lake_api` for good, so every cluster built afterwards revokes a
-- privilege it was never granted — this file asserting the absence of a grant
-- instead of declaring a reader, which is a claim it could not keep for every
-- account that is not a reader. And by this file's own rule a privilege
-- statement names a user that has to exist when it is stored, so a cluster with
-- no Lake deployed would fail the file and lose the `grafana` grants that do
-- apply there. Whether ClickHouse errors that way on a revoke is untested here
-- and wants checking before anyone promotes these three lines. The cleanup is
-- one-time work on one cluster either way, which is why it is recorded and
-- dated rather than declared.

-- THE SIX RACE GRANTS ARE WRITTEN HERE BEFORE THEY ARE APPLIED, WHICH IS THE
-- OPPOSITE ORDER FROM THE FIRST THREE AND IS THE ORDER THIS FILE ARGUES FOR.
-- The first three were applied by hand and written down afterwards, and the
-- paragraph at the top of this file is what that order cost. How long it
-- lasted is not the point and a short gap is no defence: for as long as it
-- lasted, the cluster held a grant no file named, and a rebuild in that window
-- would have come back without it. These are written down first: an
-- administrator applies the file, and the record and the cluster agree from
-- the beginning rather than after somebody reconciles them.
--
-- SO THE READER DOES NOT HOLD THEM AS OF 2026-09-22, AND WHAT SAYS SO IS A
-- SYMPTOM RATHER THAN THE CLUSTER. `malbeclabs/phoenix#290` reports a panel
-- over `recorder.feed_race` answering `497`, which is the same evidence the
-- first three grants were written from. `grafana` has no privilege on
-- `system.grants` — `SHOW ACCESS` answers `497` through the Grafana data
-- source's own credential — so the state is read with
-- `SHOW GRANTS FOR grafana;` from an administrator's session, which is the
-- session that applies this file anyway.
-- The dashboard the six are for is `malbeclabs/phoenix#291`; until they are
-- applied it renders the venue counts and nothing about the race.

-- The venue-side tables of `009`, read by the Grafana data source that backs
-- the `phoenix-venue-recorder` dashboard in `malbeclabs/infra`.
GRANT SELECT ON recorder.venue_book_top TO grafana;
GRANT SELECT ON recorder.venue_object TO grafana;
-- And `009`'s collapsed view over the first of them, for counts.
GRANT SELECT ON recorder.venue_book_top_settled TO grafana;
-- The venue side's occurrence ordinal, which the race is an aggregate over and
-- which the grant on the collapsed view beneath it does not reach.
GRANT SELECT ON recorder.venue_book_top_occurrence TO grafana;

-- The publisher side of the same race: `005`'s table, `006`'s collapse over it
-- as `010` re-states it, and `010`'s numbering on the key both sides compute.
-- A table of `005` is granted here for the first time, and the paragraph on
-- scope above says why that is a decision rather than a widening.
GRANT SELECT ON recorder.book_top TO grafana;
GRANT SELECT ON recorder.book_top_settled TO grafana;
GRANT SELECT ON recorder.publisher_book_top_occurrence TO grafana;

-- The seam both sides enter by, and the pairing over it — the two a feed-race
-- panel names, and the only two of the nine somebody writing one would think to
-- ask for.
GRANT SELECT ON recorder.feed_race_occurrence TO grafana;
GRANT SELECT ON recorder.feed_race TO grafana;
