[package]
name = "xdp-filter"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/malbeclabs/edge-multicast-ref"

[[bin]]
name = "xdp-filter"
path = "src/main.rs"

[dependencies]
aya-ebpf = "0.1"
aya-log-ebpf = "0.1"
xdp-filter-common = { path = "../common" }

[profile.release]
panic = "abort"
